---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# adapref

<!-- badges: start -->
<!-- badges: end -->

adapref has two main uses: 

- Estimation of the effective population size of a single population when there is preferential sampling [1]

- Estimation of the effective population sizes of two populations coevolving [2]. One is free to include or not preferential sampling in this second scenario

It is a package to be used jointly with phylodyn and spmrf. Many of the functions of this package have been developed starting from the work done in these two packages. We acknowledge the developers for their work. 

## Installation

1. Install (if necessary) package dependencies and helpers: `devtools`, `ape`, `spmrf`, `rstan`, `loo` and `phylodyn`.

2. Load `devtools` using `library(devtools)`.

3. Install `adapref` using

    a. `install_github("lorenzocapp/adapref")`, or

    b. `install_github("lorenzocapp/adapref", build_vignettes = TRUE)` if you want some illustrative vignettes (note: using `build_vignettes = TRUE` will make the install take longer).

## Vignettes

1. [Adaptive preferential sampling with simulated data](https://github.com/lorenzocapp/adapref/blob/master/vignettes/adapref_intro.Rmd): A short tutorial to describe the basics of the first method [1]

2. 

## References

[1] Cappello, L., Palacios, J.A. (2022) Adaptive Preferential Sampling in Phylodynamics, *Journal of Computational and Graphical Statistics*, 31, 541-552. [Link](https://www.tandfonline.com/doi/full/10.1080/10618600.2021.1987256)

[2] Cappello, L.**\*,  Kim, J.\* , Palacios, J. A., (2022+) ``Bayesian Inference of Dependent Population Dynamics in Coalescent Models." [\[biorXiv\]](https://www.biorxiv.org/content/10.1101/2022.05.22.492976v1). \* first authors
